namespace Horror.Gameplay.ObjectPooling
{
	public enum PoolType
	{
		ARROW_PROJECTILE,
		ARCHER_SKELETON,
		WARRIOR_SKELETON,
		SOUND_PLAYER,
		HEALTH_ITEM,
		ARROW_ITEM,
		PROJECTILE_COLLISION_PARTICLES,
		WARRIOR_SKELETON_SWORD,
		KING_SKELETON_SWORD
	}
}
