namespace Horror.Gameplay.Audio
{
	public enum Sound
	{
		GAME_THEME,
		UI_BUTTON_CLICK,
		PLAYER_HITTED,
		PLAYER_JUMP,
		AIM_BOW,
		PULL_ARROW,
		SHOOT_ARROW,
		SWORD_SLASH,
		MONSTER_GRUNT,
		WARRIOR_SKELETON_HITTED,
		ARCHER_SKELETON_HITTED,
		HEALTH_ITEM_PICKED,
		ARROW_ITEM_PICKED,
		ARROW_COLLISION
	}
}
